"use client";
import { Star } from "lucide-react";
import { motion, useAnimation, useInView, Variants } from "framer-motion";
import { useRef, useEffect } from "react";
import RevealOnScroll from "@/components/layout/RevealOnScroll";

const stats = [
  {
    value: "87%",
    desc: "of buyers start their search online - your website is their first impression",
  },
  {
    value: "73%",
    desc: "of sellers research agents online before making contact",
  },
  {
    value: "5x",
    desc: "more leads generated by realtor-optimized websites",
  },
];

export default function HomeTestimonials() {
  const cardsContainerRef = useRef(null);
  const isInView = useInView(cardsContainerRef, { once: true, margin: "-100px" });
  const controls = useAnimation();

  useEffect(() => {
    if (isInView) {
      controls.start("visible");
    }
  }, [isInView, controls]);

  const cardVariants: Variants = {
    hidden: { opacity: 0, y: 40 },
    visible: (i: number) => ({
      opacity: 1,
      y: 0,
      transition: {
        delay: i * 0.2,
        duration: 0.6,
        type: "spring",
        stiffness: 100,
      },
    }),
  };

  return (
    <section className="w-full bg-[#020817] py-16 px-6 md:px-0">
      <div className="max-w-7xl mx-auto">
        {/* Heading */}
        <RevealOnScroll>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold text-center mb-12 text-white">
            The Numbers Don&apos;t Lie:{" "}
            <span className="bg-gradient-to-r from-blue-500 to-white bg-clip-text text-transparent">
              Online Presence Matters
            </span>
          </h2>
        </RevealOnScroll>

        {/* Stats */}
        <div
          ref={cardsContainerRef}
          className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12 max-w-5xl mx-auto"
        >
          {stats.map((stat, i) => (
            <motion.div
              key={stat.value}
              className="bg-[#232736] rounded-xl px-8 py-10 flex flex-col items-center text-center shadow-md"
              variants={cardVariants}
              initial="hidden"
              animate={controls}
              custom={i}
            >
              <div className="text-5xl font-bold bg-gradient-to-r from-blue-500 to-white bg-clip-text text-transparent mb-2">
                {stat.value}
              </div>
              <div className="text-gray-300 text-lg">{stat.desc}</div>
            </motion.div>
          ))}
        </div>

        {/* Testimonial/Coming Soon */}
        {/* <motion.div
          className="flex justify-center"
          variants={cardVariants}
          initial="hidden"
          animate={controls}
          custom={stats.length}
        >
          <div className="bg-[#232736] rounded-xl px-8 py-10 max-w-3xl w-full text-center mx-auto shadow-lg">
            <div className="flex justify-center mb-4">
              {[...Array(5)].map((_, i) => (
                <Star key={i} className="w-6 h-6 text-yellow-400 mx-0.5" fill="#facc15" />
              ))}
            </div>
            <div className="italic text-gray-200 text-xl mb-4">
              &quot;Ready to showcase client testimonials here. This space will highlight real results: increased leads, time saved, and deals closed.&quot;
            </div>
            <div className="font-bold text-white text-lg mb-1">
              Coming Soon: Client Success Stories
            </div>
            <div className="text-gray-400 text-base">
              Real Estate Professionals, Edmonton &amp; Beyond
            </div>
          </div>
        </motion.div> */}
      </div>
    </section>
  );
}